### ISSUE TITLE
Create a navbar 

### ISSUE THREAD

**Issue by Nikhita28** [gdscjgec/gdscjgec.github.io#1]
## 🚀 Feature
Design a responsive navbar for the website. You may use bootstrap for the same. Make sure the colours align with the Google colour theme. We need to include home, events, blogs, team, contact us in the navbar.

**Comment by kashish-d** [comment]
Can I work on this one?

**Comment by tahseenzahra** [comment]
hello Nikhita! can I work on this task can you assign it to me too?

**Comment by VidhiBhatt01** [comment]
would like to work on this, please assign!

**Comment by Nikhita28** [comment]
Assigned @VidhiBhatt01, go ahead!
