### ISSUE TITLE
Seo Optimisation for the Site

### ISSUE THREAD

**Issue by imniladri** [gdscjgec/gdscjgec.github.io#11]
### Optimise the site for better performance & ranking!

- Just add all kinds of meta tags, favicon, titles, the theme color for each page for proper view in **Head**.
- Proper documentation & comments for each section in **Body**.
- Link all CSS & JS files in proper sequence according to preference in **Head**.

**Comment by niloysikdar** [comment]
Do you want to work on this issue @imniladri ?

**Comment by imniladri** [comment]
Yup, No problem I can work on it and fix it!

**Comment by niloysikdar** [comment]
Assigned @imniladri, go ahead, all the best.
