### ISSUE TITLE
Add a Projects Page

### ISSUE THREAD

**Issue by imniladri** [gdscjgec/gdscjgec.github.io#23]
## 🚀 Feature

**A Project page that will include all our projects from Github or any extra.**

**Try to use the default options we provided:**
- For colors & fonts must have a look in [`settings.css`](https://github.com/gdscjgec/gdscjgec.github.io/blob/main/css/settings.css) in the CSS directory.
- Create different files for the project page, i.e, css `project.css` & html `project.html`.
- Maintain the files & folder structure properly.

**Comment by zainulabideen1122** [comment]
Hy @imniladri! Can you assign this task to me?

**Comment by ManishOffi** [comment]
Hey Dude,
please me assign me to this topic?

**Comment by imniladri** [comment]
Will assign another if it's not done by the previous one.
