### ISSUE TITLE
Minor Styling issues in the Events Page

### ISSUE THREAD

**Issue by niloysikdar** [gdscjgec/gdscjgec.github.io#44]
## Describe the Bug 🐛

**A clear and concise description of what the bug is**:
There are some styling issues on the events page due to the subsequent merging of the pull requests #40 #42 

**To Reproduce**:

1. Go to [`events`](https://gdscjgec.github.io/pages/events.html) page

You will see some styling issues for the events cards.

@imniladri please look into this

**Comment by imniladri** [comment]
Ok sure!
