### ISSUE TITLE
Make an events page

### ISSUE THREAD

**Issue by nisha331** [gdscjgec/gdscjgec.github.io#5]
## 🚀 Feature

Create a events page where we can showcase aur of events done in GDSC JGEC .

**Comment by SoumadeepBagui409** [comment]
Can I work on it

**Comment by code-soham** [comment]
Hi ma'am I am from GDSC JGEC, could you please assign me this issue?
Thank you.

**Comment by Nikhita28** [comment]
Assigned @code-soham
