### ISSUE TITLE
Make a contact us page

### ISSUE THREAD

**Issue by Nikhita28** [gdscjgec/gdscjgec.github.io#6]
## 🚀 Feature
Make a contact us page. Add the socials of GDSC and also add a contact form.

**Comment by arijitghosh10** [comment]
Can I work on this part?

**Comment by TuhinBanerjeeCSE** [comment]
I want to work on this, I am a member of GDSC JGEC .

**Comment by Nikhita28** [comment]
Assigned. Go ahead @TuhinBanerjeeCSE !
